package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Countries was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Countries extends CayenneDataObject {

    @Deprecated
    public static final String CURRENCY_PROPERTY = "currency";
    @Deprecated
    public static final String CURRENCY_SYMBOL_PROPERTY = "currencySymbol";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CURRENCY = new Property<String>("currency");
    public static final Property<String> CURRENCY_SYMBOL = new Property<String>("currencySymbol");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");

    public void setCurrency(String currency) {
        writeProperty("currency", currency);
    }
    public String getCurrency() {
        return (String)readProperty("currency");
    }

    public void setCurrencySymbol(String currencySymbol) {
        writeProperty("currencySymbol", currencySymbol);
    }
    public String getCurrencySymbol() {
        return (String)readProperty("currencySymbol");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

}
