package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Domains was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Domains extends CayenneDataObject {

    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String VALUE_PROPERTY = "value";

    public static final String ID_PK_COLUMN = "id";
    public static final String VALUE_PK_COLUMN = "value";

    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> VALUE = new Property<String>("value");

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

}
