package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _GroupingsV was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _GroupingsV extends CayenneDataObject {

    @Deprecated
    public static final String ACTIVE_PROPERTY = "active";
    @Deprecated
    public static final String DESCRIPTION_PROPERTY = "description";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String KIND_PROPERTY = "kind";
    @Deprecated
    public static final String LANGUAGE_PROPERTY = "language";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";
    @Deprecated
    public static final String NUMBER_RANGE_PROPERTY = "numberRange";
    @Deprecated
    public static final String ORGANIZATIONS_PROPERTY = "organizations";
    @Deprecated
    public static final String PERSONS_PROPERTY = "persons";

    public static final String ID_PK_COLUMN = "id";
    public static final String LANGUAGE_PK_COLUMN = "language";

    public static final Property<Boolean> ACTIVE = new Property<Boolean>("active");
    public static final Property<String> DESCRIPTION = new Property<String>("description");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> KIND = new Property<String>("kind");
    public static final Property<String> LANGUAGE = new Property<String>("language");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");
    public static final Property<String> NUMBER_RANGE = new Property<String>("numberRange");
    public static final Property<Boolean> ORGANIZATIONS = new Property<Boolean>("organizations");
    public static final Property<Boolean> PERSONS = new Property<Boolean>("persons");

    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }

    public String getDescription() {
        return (String)readProperty("description");
    }

    public String getId() {
        return (String)readProperty("id");
    }

    public String getKind() {
        return (String)readProperty("kind");
    }

    public String getLanguage() {
        return (String)readProperty("language");
    }

    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

    public String getNumberRange() {
        return (String)readProperty("numberRange");
    }

    public Boolean getOrganizations() {
        return (Boolean)readProperty("organizations");
    }

    public Boolean getPersons() {
        return (Boolean)readProperty("persons");
    }

}
