package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Languages was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Languages extends CayenneDataObject {

    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";
    @Deprecated
    public static final String LOGON_PROPERTY = "logon";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ID = new Property<String>("id");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");
    public static final Property<Boolean> LOGON = new Property<Boolean>("logon");

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

    public void setLogon(Boolean logon) {
        writeProperty("logon", logon);
    }
    public Boolean getLogon() {
        return (Boolean)readProperty("logon");
    }

}
