package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _PartnerViews was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PartnerViews extends CayenneDataObject {

    @Deprecated
    public static final String GROUPING_PROPERTY = "grouping";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";
    @Deprecated
    public static final String TYPE_PROPERTY = "type";
    @Deprecated
    public static final String VIEW_PROPERTY = "view";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> GROUPING = new Property<String>("grouping");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");
    public static final Property<String> TYPE = new Property<String>("type");
    public static final Property<String> VIEW = new Property<String>("view");

    public void setGrouping(String grouping) {
        writeProperty("grouping", grouping);
    }
    public String getGrouping() {
        return (String)readProperty("grouping");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setView(String view) {
        writeProperty("view", view);
    }
    public String getView() {
        return (String)readProperty("view");
    }

}
