package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _RelationsT was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RelationsT extends CayenneDataObject {

    @Deprecated
    public static final String DESCRIPTION_PROPERTY = "description";
    @Deprecated
    public static final String DESCRIPTION_FROM_PROPERTY = "descriptionFrom";
    @Deprecated
    public static final String DESCRIPTION_TO_PROPERTY = "descriptionTo";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String LANGUAGE_PROPERTY = "language";

    public static final String ID_PK_COLUMN = "id";
    public static final String LANGUAGE_PK_COLUMN = "language";

    public static final Property<String> DESCRIPTION = new Property<String>("description");
    public static final Property<String> DESCRIPTION_FROM = new Property<String>("descriptionFrom");
    public static final Property<String> DESCRIPTION_TO = new Property<String>("descriptionTo");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> LANGUAGE = new Property<String>("language");

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setDescriptionFrom(String descriptionFrom) {
        writeProperty("descriptionFrom", descriptionFrom);
    }
    public String getDescriptionFrom() {
        return (String)readProperty("descriptionFrom");
    }

    public void setDescriptionTo(String descriptionTo) {
        writeProperty("descriptionTo", descriptionTo);
    }
    public String getDescriptionTo() {
        return (String)readProperty("descriptionTo");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setLanguage(String language) {
        writeProperty("language", language);
    }
    public String getLanguage() {
        return (String)readProperty("language");
    }

}
