package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Relations was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Relations extends CayenneDataObject {

    @Deprecated
    public static final String DIRECTED_PROPERTY = "directed";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";
    @Deprecated
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> DIRECTED = new Property<Boolean>("directed");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");
    public static final Property<Integer> TYPE = new Property<Integer>("type");

    public void setDirected(Boolean directed) {
        writeProperty("directed", directed);
    }
    public Boolean getDirected() {
        return (Boolean)readProperty("directed");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

    public void setType(Integer type) {
        writeProperty("type", type);
    }
    public Integer getType() {
        return (Integer)readProperty("type");
    }

}
