package at.mxerp.db.erp;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Relationships was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Relationships extends CayenneDataObject {

    @Deprecated
    public static final String CHANGED_AT_PROPERTY = "changedAt";
    @Deprecated
    public static final String CHANGED_BY_PROPERTY = "changedBy";
    @Deprecated
    public static final String CREATED_AT_PROPERTY = "createdAt";
    @Deprecated
    public static final String CREATED_BY_PROPERTY = "createdBy";
    @Deprecated
    public static final String DELETED_PROPERTY = "deleted";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String PARTNER1_PROPERTY = "partner1";
    @Deprecated
    public static final String PARTNER2_PROPERTY = "partner2";
    @Deprecated
    public static final String VALID_FROM_PROPERTY = "validFrom";
    @Deprecated
    public static final String VALID_TO_PROPERTY = "validTo";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> CHANGED_AT = new Property<Date>("changedAt");
    public static final Property<String> CHANGED_BY = new Property<String>("changedBy");
    public static final Property<Date> CREATED_AT = new Property<Date>("createdAt");
    public static final Property<String> CREATED_BY = new Property<String>("createdBy");
    public static final Property<Boolean> DELETED = new Property<Boolean>("deleted");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> PARTNER1 = new Property<String>("partner1");
    public static final Property<String> PARTNER2 = new Property<String>("partner2");
    public static final Property<Date> VALID_FROM = new Property<Date>("validFrom");
    public static final Property<Date> VALID_TO = new Property<Date>("validTo");

    public void setChangedAt(Date changedAt) {
        writeProperty("changedAt", changedAt);
    }
    public Date getChangedAt() {
        return (Date)readProperty("changedAt");
    }

    public void setChangedBy(String changedBy) {
        writeProperty("changedBy", changedBy);
    }
    public String getChangedBy() {
        return (String)readProperty("changedBy");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setCreatedBy(String createdBy) {
        writeProperty("createdBy", createdBy);
    }
    public String getCreatedBy() {
        return (String)readProperty("createdBy");
    }

    public void setDeleted(Boolean deleted) {
        writeProperty("deleted", deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty("deleted");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setPartner1(String partner1) {
        writeProperty("partner1", partner1);
    }
    public String getPartner1() {
        return (String)readProperty("partner1");
    }

    public void setPartner2(String partner2) {
        writeProperty("partner2", partner2);
    }
    public String getPartner2() {
        return (String)readProperty("partner2");
    }

    public void setValidFrom(Date validFrom) {
        writeProperty("validFrom", validFrom);
    }
    public Date getValidFrom() {
        return (Date)readProperty("validFrom");
    }

    public void setValidTo(Date validTo) {
        writeProperty("validTo", validTo);
    }
    public Date getValidTo() {
        return (Date)readProperty("validTo");
    }

}
