package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _SavedSearches was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SavedSearches extends CayenneDataObject {

    @Deprecated
    public static final String DATA_PROPERTY = "data";
    @Deprecated
    public static final String DEFAULT_PROPERTY = "default";
    @Deprecated
    public static final String ENTITY_PROPERTY = "entity";
    @Deprecated
    public static final String GLOBAL_PROPERTY = "global";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<byte[]> DATA = new Property<byte[]>("data");
    public static final Property<Boolean> DEFAULT = new Property<Boolean>("default");
    public static final Property<String> ENTITY = new Property<String>("entity");
    public static final Property<Boolean> GLOBAL = new Property<Boolean>("global");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> USER = new Property<String>("user");

    public void setData(byte[] data) {
        writeProperty("data", data);
    }
    public byte[] getData() {
        return (byte[])readProperty("data");
    }

    public void setDefault(Boolean _default) {
        writeProperty("default", _default);
    }
    public Boolean getDefault() {
        return (Boolean)readProperty("default");
    }

    public void setEntity(String entity) {
        writeProperty("entity", entity);
    }
    public String getEntity() {
        return (String)readProperty("entity");
    }

    public void setGlobal(Boolean global) {
        writeProperty("global", global);
    }
    public Boolean getGlobal() {
        return (Boolean)readProperty("global");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setUser(String user) {
        writeProperty("user", user);
    }
    public String getUser() {
        return (String)readProperty("user");
    }

}
