package at.mxerp.db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _UserPresets was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserPresets extends CayenneDataObject {

    @Deprecated
    public static final String FIELD_PROPERTY = "field";
    @Deprecated
    public static final String OBJECT_PROPERTY = "object";
    @Deprecated
    public static final String USER_PROPERTY = "user";
    @Deprecated
    public static final String VALUE_PROPERTY = "value";

    public static final String FIELD_PK_COLUMN = "field";
    public static final String OBJECT_PK_COLUMN = "object";
    public static final String USER_PK_COLUMN = "user";

    public static final Property<String> FIELD = new Property<String>("field");
    public static final Property<String> OBJECT = new Property<String>("object");
    public static final Property<String> USER = new Property<String>("user");
    public static final Property<String> VALUE = new Property<String>("value");

    public void setField(String field) {
        writeProperty("field", field);
    }
    public String getField() {
        return (String)readProperty("field");
    }

    public void setObject(String object) {
        writeProperty("object", object);
    }
    public String getObject() {
        return (String)readProperty("object");
    }

    public void setUser(String user) {
        writeProperty("user", user);
    }
    public String getUser() {
        return (String)readProperty("user");
    }

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

}
