package erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _CcAuditPos was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditPos extends CayenneDataObject {

    @Deprecated
    public static final String FIELD_PROPERTY = "field";
    @Deprecated
    public static final String GUID_PROPERTY = "guid";
    @Deprecated
    public static final String HEAD_ID_PROPERTY = "headId";
    @Deprecated
    public static final String VALUE_NEW_PROPERTY = "valueNew";
    @Deprecated
    public static final String VALUE_OLD_PROPERTY = "valueOld";
    @Deprecated
    public static final String TO_CC_AUDIT_HEAD_PROPERTY = "toCcAuditHead";

    public static final String GUID_PK_COLUMN = "GUID";

    public static final Property<String> FIELD = new Property<String>("field");
    public static final Property<String> GUID = new Property<String>("guid");
    public static final Property<String> HEAD_ID = new Property<String>("headId");
    public static final Property<String> VALUE_NEW = new Property<String>("valueNew");
    public static final Property<String> VALUE_OLD = new Property<String>("valueOld");
    public static final Property<AuditHead> TO_CC_AUDIT_HEAD = new Property<AuditHead>("toCcAuditHead");

    public void setField(String field) {
        writeProperty("field", field);
    }
    public String getField() {
        return (String)readProperty("field");
    }

    public void setGuid(String guid) {
        writeProperty("guid", guid);
    }
    public String getGuid() {
        return (String)readProperty("guid");
    }

    public void setHeadId(String headId) {
        writeProperty("headId", headId);
    }
    public String getHeadId() {
        return (String)readProperty("headId");
    }

    public void setValueNew(String valueNew) {
        writeProperty("valueNew", valueNew);
    }
    public String getValueNew() {
        return (String)readProperty("valueNew");
    }

    public void setValueOld(String valueOld) {
        writeProperty("valueOld", valueOld);
    }
    public String getValueOld() {
        return (String)readProperty("valueOld");
    }

    public void setToCcAuditHead(AuditHead toCcAuditHead) {
        setToOneTarget("toCcAuditHead", toCcAuditHead, true);
    }

    public AuditHead getToCcAuditHead() {
        return (AuditHead)readProperty("toCcAuditHead");
    }


}
