package erp;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _CcAuditHead was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditHead extends CayenneDataObject {

    @Deprecated
    public static final String ACTION_PROPERTY = "action";
    @Deprecated
    public static final String CHANGED_BY_PROPERTY = "changedBy";
    @Deprecated
    public static final String GUID_PROPERTY = "guid";
    @Deprecated
    public static final String KEY_FIELDS_PROPERTY = "keyFields";
    @Deprecated
    public static final String RECORD_ID_PROPERTY = "recordId";
    @Deprecated
    public static final String SOURCEAPP_PROPERTY = "sourceapp";
    @Deprecated
    public static final String TABLENAME_PROPERTY = "tablename";
    @Deprecated
    public static final String TIMESTAMP_PROPERTY = "timestamp";
    @Deprecated
    public static final String TRANSACTION_PROPERTY = "transaction";
    @Deprecated
    public static final String CC_AUDIT_POS_ARRAY_PROPERTY = "ccAuditPosArray";

    public static final String GUID_PK_COLUMN = "GUID";

    public static final Property<String> ACTION = new Property<String>("action");
    public static final Property<String> CHANGED_BY = new Property<String>("changedBy");
    public static final Property<String> GUID = new Property<String>("guid");
    public static final Property<String> KEY_FIELDS = new Property<String>("keyFields");
    public static final Property<String> RECORD_ID = new Property<String>("recordId");
    public static final Property<String> SOURCEAPP = new Property<String>("sourceapp");
    public static final Property<String> TABLENAME = new Property<String>("tablename");
    public static final Property<Date> TIMESTAMP = new Property<Date>("timestamp");
    public static final Property<String> TRANSACTION = new Property<String>("transaction");
    public static final Property<List<AuditPos>> CC_AUDIT_POS_ARRAY = new Property<List<AuditPos>>("ccAuditPosArray");

    public void setAction(String action) {
        writeProperty("action", action);
    }
    public String getAction() {
        return (String)readProperty("action");
    }

    public void setChangedBy(String changedBy) {
        writeProperty("changedBy", changedBy);
    }
    public String getChangedBy() {
        return (String)readProperty("changedBy");
    }

    public void setGuid(String guid) {
        writeProperty("guid", guid);
    }
    public String getGuid() {
        return (String)readProperty("guid");
    }

    public void setKeyFields(String keyFields) {
        writeProperty("keyFields", keyFields);
    }
    public String getKeyFields() {
        return (String)readProperty("keyFields");
    }

    public void setRecordId(String recordId) {
        writeProperty("recordId", recordId);
    }
    public String getRecordId() {
        return (String)readProperty("recordId");
    }

    public void setSourceapp(String sourceapp) {
        writeProperty("sourceapp", sourceapp);
    }
    public String getSourceapp() {
        return (String)readProperty("sourceapp");
    }

    public void setTablename(String tablename) {
        writeProperty("tablename", tablename);
    }
    public String getTablename() {
        return (String)readProperty("tablename");
    }

    public void setTimestamp(Date timestamp) {
        writeProperty("timestamp", timestamp);
    }
    public Date getTimestamp() {
        return (Date)readProperty("timestamp");
    }

    public void setTransaction(String transaction) {
        writeProperty("transaction", transaction);
    }
    public String getTransaction() {
        return (String)readProperty("transaction");
    }

    public void addToCcAuditPosArray(AuditPos obj) {
        addToManyTarget("ccAuditPosArray", obj, true);
    }
    public void removeFromCcAuditPosArray(AuditPos obj) {
        removeToManyTarget("ccAuditPosArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AuditPos> getCcAuditPosArray() {
        return (List<AuditPos>)readProperty("ccAuditPosArray");
    }


}
