package db.erp;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Accounts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Accounts extends CayenneDataObject {

    @Deprecated
    public static final String ACCOUNT_TYPE_PROPERTY = "accountType";
    @Deprecated
    public static final String ANNUAL_REVENUE_PROPERTY = "annualRevenue";
    @Deprecated
    public static final String ASSIGNED_USER_ID_PROPERTY = "assignedUserId";
    @Deprecated
    public static final String BILLING_ADDRESS_CITY_PROPERTY = "billingAddressCity";
    @Deprecated
    public static final String BILLING_ADDRESS_COUNTRY_PROPERTY = "billingAddressCountry";
    @Deprecated
    public static final String BILLING_ADDRESS_POSTALCODE_PROPERTY = "billingAddressPostalcode";
    @Deprecated
    public static final String BILLING_ADDRESS_STATE_PROPERTY = "billingAddressState";
    @Deprecated
    public static final String BILLING_ADDRESS_STREET_PROPERTY = "billingAddressStreet";
    @Deprecated
    public static final String CAMPAIGN_ID_PROPERTY = "campaignId";
    @Deprecated
    public static final String CREATED_BY_PROPERTY = "createdBy";
    @Deprecated
    public static final String DATE_ENTERED_PROPERTY = "dateEntered";
    @Deprecated
    public static final String DATE_MODIFIED_PROPERTY = "dateModified";
    @Deprecated
    public static final String DELETED_PROPERTY = "deleted";
    @Deprecated
    public static final String DESCRIPTION_PROPERTY = "description";
    @Deprecated
    public static final String EMPLOYEES_PROPERTY = "employees";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String INDUSTRY_PROPERTY = "industry";
    @Deprecated
    public static final String MODIFIED_USER_ID_PROPERTY = "modifiedUserId";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String OWNERSHIP_PROPERTY = "ownership";
    @Deprecated
    public static final String PARENT_ID_PROPERTY = "parentId";
    @Deprecated
    public static final String PHONE_ALTERNATE_PROPERTY = "phoneAlternate";
    @Deprecated
    public static final String PHONE_FAX_PROPERTY = "phoneFax";
    @Deprecated
    public static final String PHONE_OFFICE_PROPERTY = "phoneOffice";
    @Deprecated
    public static final String RATING_PROPERTY = "rating";
    @Deprecated
    public static final String SHIPPING_ADDRESS_CITY_PROPERTY = "shippingAddressCity";
    @Deprecated
    public static final String SHIPPING_ADDRESS_COUNTRY_PROPERTY = "shippingAddressCountry";
    @Deprecated
    public static final String SHIPPING_ADDRESS_POSTALCODE_PROPERTY = "shippingAddressPostalcode";
    @Deprecated
    public static final String SHIPPING_ADDRESS_STATE_PROPERTY = "shippingAddressState";
    @Deprecated
    public static final String SHIPPING_ADDRESS_STREET_PROPERTY = "shippingAddressStreet";
    @Deprecated
    public static final String SIC_CODE_PROPERTY = "sicCode";
    @Deprecated
    public static final String TICKER_SYMBOL_PROPERTY = "tickerSymbol";
    @Deprecated
    public static final String WEBSITE_PROPERTY = "website";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ACCOUNT_TYPE = new Property<String>("accountType");
    public static final Property<String> ANNUAL_REVENUE = new Property<String>("annualRevenue");
    public static final Property<String> ASSIGNED_USER_ID = new Property<String>("assignedUserId");
    public static final Property<String> BILLING_ADDRESS_CITY = new Property<String>("billingAddressCity");
    public static final Property<String> BILLING_ADDRESS_COUNTRY = new Property<String>("billingAddressCountry");
    public static final Property<String> BILLING_ADDRESS_POSTALCODE = new Property<String>("billingAddressPostalcode");
    public static final Property<String> BILLING_ADDRESS_STATE = new Property<String>("billingAddressState");
    public static final Property<String> BILLING_ADDRESS_STREET = new Property<String>("billingAddressStreet");
    public static final Property<String> CAMPAIGN_ID = new Property<String>("campaignId");
    public static final Property<String> CREATED_BY = new Property<String>("createdBy");
    public static final Property<Date> DATE_ENTERED = new Property<Date>("dateEntered");
    public static final Property<Date> DATE_MODIFIED = new Property<Date>("dateModified");
    public static final Property<Boolean> DELETED = new Property<Boolean>("deleted");
    public static final Property<String> DESCRIPTION = new Property<String>("description");
    public static final Property<String> EMPLOYEES = new Property<String>("employees");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> INDUSTRY = new Property<String>("industry");
    public static final Property<String> MODIFIED_USER_ID = new Property<String>("modifiedUserId");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> OWNERSHIP = new Property<String>("ownership");
    public static final Property<String> PARENT_ID = new Property<String>("parentId");
    public static final Property<String> PHONE_ALTERNATE = new Property<String>("phoneAlternate");
    public static final Property<String> PHONE_FAX = new Property<String>("phoneFax");
    public static final Property<String> PHONE_OFFICE = new Property<String>("phoneOffice");
    public static final Property<String> RATING = new Property<String>("rating");
    public static final Property<String> SHIPPING_ADDRESS_CITY = new Property<String>("shippingAddressCity");
    public static final Property<String> SHIPPING_ADDRESS_COUNTRY = new Property<String>("shippingAddressCountry");
    public static final Property<String> SHIPPING_ADDRESS_POSTALCODE = new Property<String>("shippingAddressPostalcode");
    public static final Property<String> SHIPPING_ADDRESS_STATE = new Property<String>("shippingAddressState");
    public static final Property<String> SHIPPING_ADDRESS_STREET = new Property<String>("shippingAddressStreet");
    public static final Property<String> SIC_CODE = new Property<String>("sicCode");
    public static final Property<String> TICKER_SYMBOL = new Property<String>("tickerSymbol");
    public static final Property<String> WEBSITE = new Property<String>("website");

    public void setAccountType(String accountType) {
        writeProperty("accountType", accountType);
    }
    public String getAccountType() {
        return (String)readProperty("accountType");
    }

    public void setAnnualRevenue(String annualRevenue) {
        writeProperty("annualRevenue", annualRevenue);
    }
    public String getAnnualRevenue() {
        return (String)readProperty("annualRevenue");
    }

    public void setAssignedUserId(String assignedUserId) {
        writeProperty("assignedUserId", assignedUserId);
    }
    public String getAssignedUserId() {
        return (String)readProperty("assignedUserId");
    }

    public void setBillingAddressCity(String billingAddressCity) {
        writeProperty("billingAddressCity", billingAddressCity);
    }
    public String getBillingAddressCity() {
        return (String)readProperty("billingAddressCity");
    }

    public void setBillingAddressCountry(String billingAddressCountry) {
        writeProperty("billingAddressCountry", billingAddressCountry);
    }
    public String getBillingAddressCountry() {
        return (String)readProperty("billingAddressCountry");
    }

    public void setBillingAddressPostalcode(String billingAddressPostalcode) {
        writeProperty("billingAddressPostalcode", billingAddressPostalcode);
    }
    public String getBillingAddressPostalcode() {
        return (String)readProperty("billingAddressPostalcode");
    }

    public void setBillingAddressState(String billingAddressState) {
        writeProperty("billingAddressState", billingAddressState);
    }
    public String getBillingAddressState() {
        return (String)readProperty("billingAddressState");
    }

    public void setBillingAddressStreet(String billingAddressStreet) {
        writeProperty("billingAddressStreet", billingAddressStreet);
    }
    public String getBillingAddressStreet() {
        return (String)readProperty("billingAddressStreet");
    }

    public void setCampaignId(String campaignId) {
        writeProperty("campaignId", campaignId);
    }
    public String getCampaignId() {
        return (String)readProperty("campaignId");
    }

    public void setCreatedBy(String createdBy) {
        writeProperty("createdBy", createdBy);
    }
    public String getCreatedBy() {
        return (String)readProperty("createdBy");
    }

    public void setDateEntered(Date dateEntered) {
        writeProperty("dateEntered", dateEntered);
    }
    public Date getDateEntered() {
        return (Date)readProperty("dateEntered");
    }

    public void setDateModified(Date dateModified) {
        writeProperty("dateModified", dateModified);
    }
    public Date getDateModified() {
        return (Date)readProperty("dateModified");
    }

    public void setDeleted(Boolean deleted) {
        writeProperty("deleted", deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty("deleted");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setEmployees(String employees) {
        writeProperty("employees", employees);
    }
    public String getEmployees() {
        return (String)readProperty("employees");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setIndustry(String industry) {
        writeProperty("industry", industry);
    }
    public String getIndustry() {
        return (String)readProperty("industry");
    }

    public void setModifiedUserId(String modifiedUserId) {
        writeProperty("modifiedUserId", modifiedUserId);
    }
    public String getModifiedUserId() {
        return (String)readProperty("modifiedUserId");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setOwnership(String ownership) {
        writeProperty("ownership", ownership);
    }
    public String getOwnership() {
        return (String)readProperty("ownership");
    }

    public void setParentId(String parentId) {
        writeProperty("parentId", parentId);
    }
    public String getParentId() {
        return (String)readProperty("parentId");
    }

    public void setPhoneAlternate(String phoneAlternate) {
        writeProperty("phoneAlternate", phoneAlternate);
    }
    public String getPhoneAlternate() {
        return (String)readProperty("phoneAlternate");
    }

    public void setPhoneFax(String phoneFax) {
        writeProperty("phoneFax", phoneFax);
    }
    public String getPhoneFax() {
        return (String)readProperty("phoneFax");
    }

    public void setPhoneOffice(String phoneOffice) {
        writeProperty("phoneOffice", phoneOffice);
    }
    public String getPhoneOffice() {
        return (String)readProperty("phoneOffice");
    }

    public void setRating(String rating) {
        writeProperty("rating", rating);
    }
    public String getRating() {
        return (String)readProperty("rating");
    }

    public void setShippingAddressCity(String shippingAddressCity) {
        writeProperty("shippingAddressCity", shippingAddressCity);
    }
    public String getShippingAddressCity() {
        return (String)readProperty("shippingAddressCity");
    }

    public void setShippingAddressCountry(String shippingAddressCountry) {
        writeProperty("shippingAddressCountry", shippingAddressCountry);
    }
    public String getShippingAddressCountry() {
        return (String)readProperty("shippingAddressCountry");
    }

    public void setShippingAddressPostalcode(String shippingAddressPostalcode) {
        writeProperty("shippingAddressPostalcode", shippingAddressPostalcode);
    }
    public String getShippingAddressPostalcode() {
        return (String)readProperty("shippingAddressPostalcode");
    }

    public void setShippingAddressState(String shippingAddressState) {
        writeProperty("shippingAddressState", shippingAddressState);
    }
    public String getShippingAddressState() {
        return (String)readProperty("shippingAddressState");
    }

    public void setShippingAddressStreet(String shippingAddressStreet) {
        writeProperty("shippingAddressStreet", shippingAddressStreet);
    }
    public String getShippingAddressStreet() {
        return (String)readProperty("shippingAddressStreet");
    }

    public void setSicCode(String sicCode) {
        writeProperty("sicCode", sicCode);
    }
    public String getSicCode() {
        return (String)readProperty("sicCode");
    }

    public void setTickerSymbol(String tickerSymbol) {
        writeProperty("tickerSymbol", tickerSymbol);
    }
    public String getTickerSymbol() {
        return (String)readProperty("tickerSymbol");
    }

    public void setWebsite(String website) {
        writeProperty("website", website);
    }
    public String getWebsite() {
        return (String)readProperty("website");
    }

}
