package db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Groupings was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Groupings extends CayenneDataObject {

    @Deprecated
    public static final String ACTIVE_PROPERTY = "active";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String KIND_PROPERTY = "kind";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";

    public static final String ID_PK_COLUMN = "id";
    public static final String KIND_PK_COLUMN = "kind";

    public static final Property<Boolean> ACTIVE = new Property<Boolean>("active");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> KIND = new Property<String>("kind");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");

    public void setActive(Boolean active) {
        writeProperty("active", active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setKind(String kind) {
        writeProperty("kind", kind);
    }
    public String getKind() {
        return (String)readProperty("kind");
    }

    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

}
