package db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _NumberRanges was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NumberRanges extends CayenneDataObject {

    @Deprecated
    public static final String ACTIVE_PROPERTY = "active";
    @Deprecated
    public static final String ACTUAL_PROPERTY = "actual";
    @Deprecated
    public static final String DIGITS_PROPERTY = "digits";
    @Deprecated
    public static final String ENTITY_PROPERTY = "entity";
    @Deprecated
    public static final String HIGH_PROPERTY = "high";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String KEY_PROPERTY = "key";
    @Deprecated
    public static final String LOCKED_PROPERTY = "locked";
    @Deprecated
    public static final String LOW_PROPERTY = "low";
    @Deprecated
    public static final String PER_YEAR_PROPERTY = "perYear";
    @Deprecated
    public static final String PREFIX_PROPERTY = "prefix";
    @Deprecated
    public static final String ROLLING_PROPERTY = "rolling";
    @Deprecated
    public static final String WARN_LEVEL_PROPERTY = "warnLevel";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = new Property<Boolean>("active");
    public static final Property<Integer> ACTUAL = new Property<Integer>("actual");
    public static final Property<Integer> DIGITS = new Property<Integer>("digits");
    public static final Property<String> ENTITY = new Property<String>("entity");
    public static final Property<Integer> HIGH = new Property<Integer>("high");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> KEY = new Property<String>("key");
    public static final Property<Boolean> LOCKED = new Property<Boolean>("locked");
    public static final Property<Integer> LOW = new Property<Integer>("low");
    public static final Property<Boolean> PER_YEAR = new Property<Boolean>("perYear");
    public static final Property<String> PREFIX = new Property<String>("prefix");
    public static final Property<Boolean> ROLLING = new Property<Boolean>("rolling");
    public static final Property<Integer> WARN_LEVEL = new Property<Integer>("warnLevel");

    public void setActive(Boolean active) {
        writeProperty("active", active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }

    public void setActual(Integer actual) {
        writeProperty("actual", actual);
    }
    public Integer getActual() {
        return (Integer)readProperty("actual");
    }

    public void setDigits(Integer digits) {
        writeProperty("digits", digits);
    }
    public Integer getDigits() {
        return (Integer)readProperty("digits");
    }

    public void setEntity(String entity) {
        writeProperty("entity", entity);
    }
    public String getEntity() {
        return (String)readProperty("entity");
    }

    public void setHigh(Integer high) {
        writeProperty("high", high);
    }
    public Integer getHigh() {
        return (Integer)readProperty("high");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setKey(String key) {
        writeProperty("key", key);
    }
    public String getKey() {
        return (String)readProperty("key");
    }

    public void setLocked(Boolean locked) {
        writeProperty("locked", locked);
    }
    public Boolean getLocked() {
        return (Boolean)readProperty("locked");
    }

    public void setLow(Integer low) {
        writeProperty("low", low);
    }
    public Integer getLow() {
        return (Integer)readProperty("low");
    }

    public void setPerYear(Boolean perYear) {
        writeProperty("perYear", perYear);
    }
    public Boolean getPerYear() {
        return (Boolean)readProperty("perYear");
    }

    public void setPrefix(String prefix) {
        writeProperty("prefix", prefix);
    }
    public String getPrefix() {
        return (String)readProperty("prefix");
    }

    public void setRolling(Boolean rolling) {
        writeProperty("rolling", rolling);
    }
    public Boolean getRolling() {
        return (Boolean)readProperty("rolling");
    }

    public void setWarnLevel(Integer warnLevel) {
        writeProperty("warnLevel", warnLevel);
    }
    public Integer getWarnLevel() {
        return (Integer)readProperty("warnLevel");
    }

    protected abstract void onPostPersist();

    protected abstract void onPostUpdate();

}
