package db.erp;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Partners was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Partners extends CayenneDataObject {

    @Deprecated
    public static final String BILLING_ADDR_CITY_PROPERTY = "billingAddrCity";
    @Deprecated
    public static final String BILLING_ADDR_COUNTRY_PROPERTY = "billingAddrCountry";
    @Deprecated
    public static final String BILLING_ADDR_PB_PROPERTY = "billingAddrPb";
    @Deprecated
    public static final String BILLING_ADDR_PB_PC_PROPERTY = "billingAddrPbPc";
    @Deprecated
    public static final String BILLING_ADDR_PC_PROPERTY = "billingAddrPc";
    @Deprecated
    public static final String BILLING_ADDR_STATE_PROPERTY = "billingAddrState";
    @Deprecated
    public static final String BILLING_ADDR_STREET_PROPERTY = "billingAddrStreet";
    @Deprecated
    public static final String BIRTHDATE_PROPERTY = "birthdate";
    @Deprecated
    public static final String CHANGED_AT_PROPERTY = "changedAt";
    @Deprecated
    public static final String CHANGED_BY_PROPERTY = "changedBy";
    @Deprecated
    public static final String CORR_LANGUAGE_PROPERTY = "corrLanguage";
    @Deprecated
    public static final String CREATED_AT_PROPERTY = "createdAt";
    @Deprecated
    public static final String CREATED_BY_PROPERTY = "createdBy";
    @Deprecated
    public static final String DELETED_PROPERTY = "deleted";
    @Deprecated
    public static final String EMAIL_PROPERTY = "email";
    @Deprecated
    public static final String GROUPING_PROPERTY = "grouping";
    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String INDUSTRY_PROPERTY = "industry";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String NAME_FIRST_PROPERTY = "nameFirst";
    @Deprecated
    public static final String NAME_LAST_PROPERTY = "nameLast";
    @Deprecated
    public static final String NAME_ORG1_PROPERTY = "nameOrg1";
    @Deprecated
    public static final String NAME_ORG2_PROPERTY = "nameOrg2";
    @Deprecated
    public static final String PARTNER_NO_PROPERTY = "partnerNo";
    @Deprecated
    public static final String PHONE_FAX_PROPERTY = "phoneFax";
    @Deprecated
    public static final String PHONE_MOBILE_PROPERTY = "phoneMobile";
    @Deprecated
    public static final String PHONE_OFFICE_PROPERTY = "phoneOffice";
    @Deprecated
    public static final String SALUTATION_PROPERTY = "salutation";
    @Deprecated
    public static final String SHIPPING_ADDR_CITY_PROPERTY = "shippingAddrCity";
    @Deprecated
    public static final String SHIPPING_ADDR_COUNTRY_PROPERTY = "shippingAddrCountry";
    @Deprecated
    public static final String SHIPPING_ADDR_PB_PROPERTY = "shippingAddrPb";
    @Deprecated
    public static final String SHIPPING_ADDR_PB_PC_PROPERTY = "shippingAddrPbPc";
    @Deprecated
    public static final String SHIPPING_ADDR_PC_PROPERTY = "shippingAddrPc";
    @Deprecated
    public static final String SHIPPING_ADDR_STATE_PROPERTY = "shippingAddrState";
    @Deprecated
    public static final String SHIPPING_ADDR_STREET_PROPERTY = "shippingAddrStreet";
    @Deprecated
    public static final String SOURCE_PROPERTY = "source";
    @Deprecated
    public static final String TYPE_PROPERTY = "type";
    @Deprecated
    public static final String VAT_NO_PROPERTY = "vatNo";
    @Deprecated
    public static final String WEBSITE_PROPERTY = "website";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> BILLING_ADDR_CITY = new Property<String>("billingAddrCity");
    public static final Property<String> BILLING_ADDR_COUNTRY = new Property<String>("billingAddrCountry");
    public static final Property<String> BILLING_ADDR_PB = new Property<String>("billingAddrPb");
    public static final Property<String> BILLING_ADDR_PB_PC = new Property<String>("billingAddrPbPc");
    public static final Property<String> BILLING_ADDR_PC = new Property<String>("billingAddrPc");
    public static final Property<String> BILLING_ADDR_STATE = new Property<String>("billingAddrState");
    public static final Property<String> BILLING_ADDR_STREET = new Property<String>("billingAddrStreet");
    public static final Property<Date> BIRTHDATE = new Property<Date>("birthdate");
    public static final Property<Date> CHANGED_AT = new Property<Date>("changedAt");
    public static final Property<String> CHANGED_BY = new Property<String>("changedBy");
    public static final Property<String> CORR_LANGUAGE = new Property<String>("corrLanguage");
    public static final Property<Date> CREATED_AT = new Property<Date>("createdAt");
    public static final Property<String> CREATED_BY = new Property<String>("createdBy");
    public static final Property<Boolean> DELETED = new Property<Boolean>("deleted");
    public static final Property<String> EMAIL = new Property<String>("email");
    public static final Property<String> GROUPING = new Property<String>("grouping");
    public static final Property<String> ID = new Property<String>("id");
    public static final Property<String> INDUSTRY = new Property<String>("industry");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> NAME_FIRST = new Property<String>("nameFirst");
    public static final Property<String> NAME_LAST = new Property<String>("nameLast");
    public static final Property<String> NAME_ORG1 = new Property<String>("nameOrg1");
    public static final Property<String> NAME_ORG2 = new Property<String>("nameOrg2");
    public static final Property<String> PARTNER_NO = new Property<String>("partnerNo");
    public static final Property<String> PHONE_FAX = new Property<String>("phoneFax");
    public static final Property<String> PHONE_MOBILE = new Property<String>("phoneMobile");
    public static final Property<String> PHONE_OFFICE = new Property<String>("phoneOffice");
    public static final Property<String> SALUTATION = new Property<String>("salutation");
    public static final Property<String> SHIPPING_ADDR_CITY = new Property<String>("shippingAddrCity");
    public static final Property<String> SHIPPING_ADDR_COUNTRY = new Property<String>("shippingAddrCountry");
    public static final Property<String> SHIPPING_ADDR_PB = new Property<String>("shippingAddrPb");
    public static final Property<String> SHIPPING_ADDR_PB_PC = new Property<String>("shippingAddrPbPc");
    public static final Property<String> SHIPPING_ADDR_PC = new Property<String>("shippingAddrPc");
    public static final Property<String> SHIPPING_ADDR_STATE = new Property<String>("shippingAddrState");
    public static final Property<String> SHIPPING_ADDR_STREET = new Property<String>("shippingAddrStreet");
    public static final Property<String> SOURCE = new Property<String>("source");
    public static final Property<String> TYPE = new Property<String>("type");
    public static final Property<String> VAT_NO = new Property<String>("vatNo");
    public static final Property<String> WEBSITE = new Property<String>("website");

    public void setBillingAddrCity(String billingAddrCity) {
        writeProperty("billingAddrCity", billingAddrCity);
    }
    public String getBillingAddrCity() {
        return (String)readProperty("billingAddrCity");
    }

    public void setBillingAddrCountry(String billingAddrCountry) {
        writeProperty("billingAddrCountry", billingAddrCountry);
    }
    public String getBillingAddrCountry() {
        return (String)readProperty("billingAddrCountry");
    }

    public void setBillingAddrPb(String billingAddrPb) {
        writeProperty("billingAddrPb", billingAddrPb);
    }
    public String getBillingAddrPb() {
        return (String)readProperty("billingAddrPb");
    }

    public void setBillingAddrPbPc(String billingAddrPbPc) {
        writeProperty("billingAddrPbPc", billingAddrPbPc);
    }
    public String getBillingAddrPbPc() {
        return (String)readProperty("billingAddrPbPc");
    }

    public void setBillingAddrPc(String billingAddrPc) {
        writeProperty("billingAddrPc", billingAddrPc);
    }
    public String getBillingAddrPc() {
        return (String)readProperty("billingAddrPc");
    }

    public void setBillingAddrState(String billingAddrState) {
        writeProperty("billingAddrState", billingAddrState);
    }
    public String getBillingAddrState() {
        return (String)readProperty("billingAddrState");
    }

    public void setBillingAddrStreet(String billingAddrStreet) {
        writeProperty("billingAddrStreet", billingAddrStreet);
    }
    public String getBillingAddrStreet() {
        return (String)readProperty("billingAddrStreet");
    }

    public void setBirthdate(Date birthdate) {
        writeProperty("birthdate", birthdate);
    }
    public Date getBirthdate() {
        return (Date)readProperty("birthdate");
    }

    public void setChangedAt(Date changedAt) {
        writeProperty("changedAt", changedAt);
    }
    public Date getChangedAt() {
        return (Date)readProperty("changedAt");
    }

    public void setChangedBy(String changedBy) {
        writeProperty("changedBy", changedBy);
    }
    public String getChangedBy() {
        return (String)readProperty("changedBy");
    }

    public void setCorrLanguage(String corrLanguage) {
        writeProperty("corrLanguage", corrLanguage);
    }
    public String getCorrLanguage() {
        return (String)readProperty("corrLanguage");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setCreatedBy(String createdBy) {
        writeProperty("createdBy", createdBy);
    }
    public String getCreatedBy() {
        return (String)readProperty("createdBy");
    }

    public void setDeleted(Boolean deleted) {
        writeProperty("deleted", deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty("deleted");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setGrouping(String grouping) {
        writeProperty("grouping", grouping);
    }
    public String getGrouping() {
        return (String)readProperty("grouping");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setIndustry(String industry) {
        writeProperty("industry", industry);
    }
    public String getIndustry() {
        return (String)readProperty("industry");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNameFirst(String nameFirst) {
        writeProperty("nameFirst", nameFirst);
    }
    public String getNameFirst() {
        return (String)readProperty("nameFirst");
    }

    public void setNameLast(String nameLast) {
        writeProperty("nameLast", nameLast);
    }
    public String getNameLast() {
        return (String)readProperty("nameLast");
    }

    public void setNameOrg1(String nameOrg1) {
        writeProperty("nameOrg1", nameOrg1);
    }
    public String getNameOrg1() {
        return (String)readProperty("nameOrg1");
    }

    public void setNameOrg2(String nameOrg2) {
        writeProperty("nameOrg2", nameOrg2);
    }
    public String getNameOrg2() {
        return (String)readProperty("nameOrg2");
    }

    public void setPartnerNo(String partnerNo) {
        writeProperty("partnerNo", partnerNo);
    }
    public String getPartnerNo() {
        return (String)readProperty("partnerNo");
    }

    public void setPhoneFax(String phoneFax) {
        writeProperty("phoneFax", phoneFax);
    }
    public String getPhoneFax() {
        return (String)readProperty("phoneFax");
    }

    public void setPhoneMobile(String phoneMobile) {
        writeProperty("phoneMobile", phoneMobile);
    }
    public String getPhoneMobile() {
        return (String)readProperty("phoneMobile");
    }

    public void setPhoneOffice(String phoneOffice) {
        writeProperty("phoneOffice", phoneOffice);
    }
    public String getPhoneOffice() {
        return (String)readProperty("phoneOffice");
    }

    public void setSalutation(String salutation) {
        writeProperty("salutation", salutation);
    }
    public String getSalutation() {
        return (String)readProperty("salutation");
    }

    public void setShippingAddrCity(String shippingAddrCity) {
        writeProperty("shippingAddrCity", shippingAddrCity);
    }
    public String getShippingAddrCity() {
        return (String)readProperty("shippingAddrCity");
    }

    public void setShippingAddrCountry(String shippingAddrCountry) {
        writeProperty("shippingAddrCountry", shippingAddrCountry);
    }
    public String getShippingAddrCountry() {
        return (String)readProperty("shippingAddrCountry");
    }

    public void setShippingAddrPb(String shippingAddrPb) {
        writeProperty("shippingAddrPb", shippingAddrPb);
    }
    public String getShippingAddrPb() {
        return (String)readProperty("shippingAddrPb");
    }

    public void setShippingAddrPbPc(String shippingAddrPbPc) {
        writeProperty("shippingAddrPbPc", shippingAddrPbPc);
    }
    public String getShippingAddrPbPc() {
        return (String)readProperty("shippingAddrPbPc");
    }

    public void setShippingAddrPc(String shippingAddrPc) {
        writeProperty("shippingAddrPc", shippingAddrPc);
    }
    public String getShippingAddrPc() {
        return (String)readProperty("shippingAddrPc");
    }

    public void setShippingAddrState(String shippingAddrState) {
        writeProperty("shippingAddrState", shippingAddrState);
    }
    public String getShippingAddrState() {
        return (String)readProperty("shippingAddrState");
    }

    public void setShippingAddrStreet(String shippingAddrStreet) {
        writeProperty("shippingAddrStreet", shippingAddrStreet);
    }
    public String getShippingAddrStreet() {
        return (String)readProperty("shippingAddrStreet");
    }

    public void setSource(String source) {
        writeProperty("source", source);
    }
    public String getSource() {
        return (String)readProperty("source");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setVatNo(String vatNo) {
        writeProperty("vatNo", vatNo);
    }
    public String getVatNo() {
        return (String)readProperty("vatNo");
    }

    public void setWebsite(String website) {
        writeProperty("website", website);
    }
    public String getWebsite() {
        return (String)readProperty("website");
    }

}
