package db.erp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import db.enums.PartnerType;

/**
 * Class _PartnerViews was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PartnerViews extends CayenneDataObject {

    @Deprecated
    public static final String GROUPING_PROPERTY = "grouping";
    @Deprecated
    public static final String TYPE_PROPERTY = "type";
    @Deprecated
    public static final String VIEW_PROPERTY = "view";

    public static final String GROUPING_PK_COLUMN = "grouping";
    public static final String TYPE_PK_COLUMN = "type";

    public static final Property<String> GROUPING = new Property<String>("grouping");
    public static final Property<PartnerType> TYPE = new Property<PartnerType>("type");
    public static final Property<String> VIEW = new Property<String>("view");

    public void setGrouping(String grouping) {
        writeProperty("grouping", grouping);
    }
    public String getGrouping() {
        return (String)readProperty("grouping");
    }

    public void setType(PartnerType type) {
        writeProperty("type", type);
    }
    public PartnerType getType() {
        return (PartnerType)readProperty("type");
    }

    public void setView(String view) {
        writeProperty("view", view);
    }
    public String getView() {
        return (String)readProperty("view");
    }

}
